title: Hangbok Lee
author: Lee, Hangbok
email: leehangbok2009@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Although it hasn't been long since I started my career as a developer,
  I want to enjoy it and move on. Outside of engineering, i'm interested
  in a variety of studies, including mathematics, science, management and economics.
  I think all fields are connected. I hope you don't hesitate to contact me if you are
  people who want to discuss about a great opportunity for connection

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    github:  https://github.com/hangpy
    # rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: https://www.instagram.com/hangbuk/
    linkedin: https://www.linkedin.com/in/hangbok-lee-76b70513b/
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
